// Code generated by tools/themegen. DO NOT EDIT.

package web

// themeChoices are the picker entries: our pair first, then Omarchy's themes.
var themeChoices = []themeChoice{
	{"light", "doesitomarchy light", false},
	{"dark", "doesitomarchy dark", true},
	{"catppuccin-latte", "Catppuccin Latte", false},
	{"catppuccin", "Catppuccin", true},
	{"ethereal", "Ethereal", true},
	{"everforest", "Everforest", true},
	{"flexoki-light", "Flexoki Light", false},
	{"gruvbox", "Gruvbox", true},
	{"hackerman", "Hackerman", true},
	{"kanagawa", "Kanagawa", true},
	{"last-horizon", "Last Horizon", true},
	{"lumon", "Lumon", true},
	{"lupine", "Lupine", false},
	{"matte-black", "Matte Black", true},
	{"miasma", "Miasma", true},
	{"nord", "Nord", true},
	{"osaka-jade", "Osaka Jade", true},
	{"retro-82", "Retro 82", true},
	{"ristretto", "Ristretto", true},
	{"rose-pine", "Rosé Pine", false},
	{"solitude", "Solitude", true},
	{"tokyo-night", "Tokyo Night", true},
	{"vantablack", "Vantablack", true},
	{"white", "White", false},
}
