// Command themegen writes internal/web/static/themes.css, the code-sample
// colours in internal/web/static/syntax.css, and internal/web/themes_gen.go from the vendored Omarchy palettes in
// themes/omarchy plus the site's own default pair. Run from the repo root:
//
//	go run ./tools/themegen
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/doesitomarchy/doesitomarchy/internal/theme"
)

func main() {
	if err := run("themes/omarchy", "internal/web/static/themes.css", "internal/web/static/syntax.css", "internal/web/themes_gen.go"); err != nil {
		fmt.Fprintln(os.Stderr, "themegen:", err)
		os.Exit(1)
	}
}

func run(srcDir, cssOut, synOut, goOut string) error {
	files, err := filepath.Glob(filepath.Join(srcDir, "*.toml"))
	if err != nil {
		return err
	}
	sort.Strings(files)
	var themes []*theme.Theme
	for _, f := range files {
		r, err := os.Open(f)
		if err != nil {
			return err
		}
		t, err := theme.FromOmarchy(strings.TrimSuffix(filepath.Base(f), ".toml"), r)
		r.Close()
		if err != nil {
			return err
		}
		themes = append(themes, t)
	}
	light, dark := theme.Defaults()
	if err := os.WriteFile(cssOut, []byte(theme.CSS(light, dark, themes)), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(synOut, []byte(theme.SyntaxCSS(light, dark, themes)), 0o644); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("// Code generated by tools/themegen. DO NOT EDIT.\n\npackage web\n\n")
	b.WriteString("// themeChoices are the picker entries: our pair first, then Omarchy's themes.\n")
	b.WriteString("var themeChoices = []themeChoice{\n")
	for _, t := range append([]*theme.Theme{light, dark}, themes...) {
		fmt.Fprintf(&b, "\t{%q, %q, %v},\n", t.Key, t.Name, t.Dark)
	}
	b.WriteString("}\n")
	if err := os.WriteFile(goOut, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("themegen: %d Omarchy themes + default pair → %s, %s, %s\n", len(themes), cssOut, synOut, goOut)
	return nil
}
