package catalog

import (
	"errors"
	"io/fs"
	"path"
	"regexp"
	"sort"
	"strings"
)

// Port map drawings (PLAN.md §27): data/portmaps/<key>.svg is the site
// flavour of a release's drawing and data/portmaps/download/<key>.svg the
// standalone one, both generated by omarchaeology gen/portmaps.py -site. The
// key is <FileSlug(identifier)>_<release ID>.

var rePortConn = regexp.MustCompile(`class="pm-port" data-conn="([a-z]+-[0-9]+)"`)

// PortmapKey is the drawing key for a release.
func PortmapKey(identifier, release string) string { return FileSlug(identifier) + "_" + release }

func (l *loader) loadPortmaps() {
	entries, err := fs.ReadDir(l.fsys, "portmaps")
	if errors.Is(err, fs.ErrNotExist) {
		return
	}
	if err != nil {
		l.errf("portmaps", "%v", err)
		return
	}
	l.cat.Portmaps = map[string]*Portmap{}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || path.Ext(name) != ".svg" {
			continue
		}
		p := path.Join("portmaps", name)
		key := strings.TrimSuffix(name, ".svg")
		site, err := fs.ReadFile(l.fsys, p)
		if err != nil {
			l.errf(p, "%v", err)
			continue
		}
		dl, err := fs.ReadFile(l.fsys, path.Join("portmaps", "download", name))
		if err != nil {
			l.errf(p, "no standalone copy in portmaps/download: %v", err)
			continue
		}
		if strings.Contains(string(site), "<style") || strings.Contains(string(site), "style=") {
			l.errf(p, "the site flavour must not carry styles (the site's CSP forbids inline styles)")
		}
		pm := &Portmap{Key: key, Site: site, Download: dl}
		for _, m := range rePortConn.FindAllSubmatch(site, -1) {
			pm.Conns = append(pm.Conns, string(m[1]))
		}
		l.cat.Portmaps[key] = pm
	}
}

// matchPortmap attaches the release's drawing to a configuration whose layout
// it shows: the drawing's ports must be exactly the configuration's
// connectors. It returns the drawing's key when one exists, matched or not.
func (l *loader) matchPortmap(file, identifier, release string, cfg *Config) string {
	key := PortmapKey(identifier, release)
	pm := l.cat.Portmaps[key]
	if pm == nil {
		return ""
	}
	want := make([]string, 0, len(cfg.Connectors))
	for _, cn := range cfg.Connectors {
		want = append(want, cn.ID)
	}
	got := append([]string(nil), pm.Conns...)
	sort.Strings(want)
	sort.Strings(got)
	if strings.Join(want, " ") != strings.Join(got, " ") {
		l.errf(path.Join("portmaps", key+".svg"), "its ports (%s) don't match %s's layout in %s (%s)",
			strings.Join(got, " "), cfg.ID, file, strings.Join(want, " "))
		return key
	}
	cfg.Portmap = key
	return key
}
